### ISSUE TITLE
Searching for the number on the line after "CONTROL_TERMINATION"

### ISSUE THREAD

**Issue by lomusso** [lomusso/Spring-2015---Learning-Python#1]
I can get it to print the line with these words, by just using 'line' as the second argument of my re.search command.  But how do I search for the line after this one since I don't know exactly what I am searching for?

**Comment by mlp6** [comment]
You have found the correct line based on a string match, which is good!  In my email, I specified that the item of interest would be the first entry, which is in a comma-separated line... does that help clarify what you might want to do?  Something to look up... python string split method: https://docs.python.org/2/library/string.html

**Comment by lomusso** [comment]
Yes, that helps.  Thank you!
